name: Release Workflows

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: metadata
        id: metadata
        run: |
          echo release_tag=v$(date '+%Y.%m.%d') >> $GITHUB_OUTPUT
      - name: repo state
        id: repo-state
        run: |
          last_release=$(gh release view --json tagName --jq .tagName)
          head_ref=$(git rev-parse HEAD)
          ahead_by=$(gh api "repos/${{ github.repository }}/compare/$last_release...$head_ref" --jq .ahead_by)
          echo ahead_by=$ahead_by >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: release
        if: ${{ steps.repo-state.outputs.ahead_by > 0 }}
        run: |
          gh release create ${{ steps.metadata.outputs.release_tag }} \
            --fail-on-no-commits \
            --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          
